Fixed what looks like a bug causing AttributeError: 'bool' object has no attribute 'get' in line 327: LOGGER.debug('Testing {} host(s)'.format(len(_status.get('endpoints')))) AttributeError: 'bool' object has no attribute 'get' ; Also remove a couple of seemingly unneeded lines of code